pipeline {
	agent any

	stages {
		

		stage('Verify Files') {
			steps {
				sh 'pwd'
				sh 'ls -R'
			}
		}

		stage('Build Docker Image') {
			steps {
				sh 'docker build -t portfolio-app -f docker/Dockerfile .'
			}
		}

		stage('Stop Old Container') {
			steps {
				sh 'docker stop portfolio-container || true'
				sh 'docker rm portfolio-container || true'
			}
		}

		stage('Run New Container') {
			steps {
				sh 'docker run -d -p 5000:5000 --name portfolio-container portfolio-app'
			}
		}
	}
}
